# Generated by Django 4.2 on 2024-05-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
